### PR TITLE
CTF platform: update manual. (#105)

### PR DESCRIPTION
**Pull request by cole-wustl**
* Add videos and screenshots
* Update mapping from SEED Labs to CTF challenges
* Put entire manual in .md format.
Co-authored-by: Dylan Simmons <dylan.simmons@wustl.edu>

### CODE REVIEW

**Review by simmons-wustl — DISMISSED** [review]
Looks good

**Comment by simmons-wustl** [comment]
I'm a little confused by what GitHub is showing on "Files changed" preview...
On our repo's `main` branch, the file `ctf/manual/ctf_manual.tex` is already deleted, but GitHub is showing that this pull request will delete it.
Also, it looks like most of the proposed changes to `ctf/README.md` are already on our `main` branch.

@cole-wustl does this make sense to you?

**Review by simmons-wustl — APPROVED** [review]
I'm still not 100% sure as to how the two repos diverged, but I think it has to do with not merging `seed-labs/master` branch into `seed-labs_CTF/main` branch before merging `seed-labs_CTF/main` branch into `seed-labs/master`. Anyways, the merge conflict has been resolved so GitHub says this won't change any files, will just be adding to the commit history so looks good!

**Comment by cole-wustl** [comment]
Awesome, thank you!

**Pull request merged**
